name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main  # or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: List directory contents
      run: ls -la

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Debug - Print working directory
      run: pwd

    - name: Debug - List directory contents
      run: ls -la

    - name: Debug - Find requirements.txt
      run: find . -name requirements.txt

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/yasha-points:latest

    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/yasha-points:latest
          docker stop yasha-points || true
          docker rm yasha-points || true
          docker run -d --name yasha-points \
            -p 8000:8000 \
            --add-host=host.docker.internal:host-gateway \
            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            ${{ secrets.DOCKERHUB_USERNAME }}/yasha-points:latest
